### ISSUE TITLE
Example django app missing

### ISSUE THREAD

**Issue by sidpat** [MetaMetricsInc/django-warrant#1]
It is mentioned in the readme file that - 

"Check the django/demo directory for an example app with a login and user details page."

This directory is not present in the repository. Would be awesome if this could be added.
Thanks.

**Comment by rrmerugu** [comment]
+1

**Comment by codyja** [comment]
+1 please. THANKS!

**Comment by yevgeniy-valeyev** [comment]
+1

**Comment by bjinwright** [comment]
It is the cdu directory.
