### ISSUE TITLE
Cannot find or access user tokens

### ISSUE THREAD

**Issue by dgonzo** [MetaMetricsInc/django-warrant#2]
Really appreciate the effort on this project. I've not spent much time in Django and this has been super helpful.

I'm trying to access the user tokens.

I see that the tokens are being added to the session [here.](https://github.com/MetaMetricsInc/django-warrant/blob/89d7a72083f76033e16387e4a4b88b4b38520370/django_warrant/__init__.py)

However, looking at the session I don't see them e.g.:

``` python
class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    def def get(self, request, *args, **kwargs):
        return Response(dir(request.session))
```

This is a good start. I don't know if your team has any further cycles to spare on maintaining this. If not my team and I are happy to jump in. Let me know how I can be helpful.

**Comment by quenbi** [comment]
In your settings file, the authentication backend must be 'warrant.django.backend.CognitoBackend'. In the tuto, it is 'django_warrant.backend.CognitoBackend', so it doesn't match with the if condition in the __init__.py file.

I've changed the settings and I got the tokens.

**Comment by bjinwright** [comment]
We changed the string in 84a6b443b2bdb5896f09fb98d8410114087f73f5

**Comment by ripundeep** [comment]
@dgonzo  I have followed the cdu directory as an example but unable to get its working.  Can you please guide me how to proceed.
