### ISSUE TITLE
Struggling with cdu example app

### ISSUE THREAD

**Issue by mr337** [MetaMetricsInc/django-warrant#8]
I am not for sure how to integrate this into our application or how to run the cdu example app.

I created a venv, installed django-warrant as a package that brought in django et all.

Then when I run the django app I can visit localhost:8000/admin, but localhost:8000/accounts/login returns
```
django.template.exceptions.TemplateDoesNotExist: warrant/login.html
[29/Jun/2018 19:41:16] "GET /accounts/login/?next=/accounts/profile/ HTTP/1.1" 500 85973
```

and debug page for django.

Am I doing something wrong?

**Comment by mr337** [comment]
Finally wrapped by head around it. Still can't get the cdu example to work, but did get it implemented in my application.

**Comment by ripundeep** [comment]
@mr337  I am stuck in same situation;  Have you sorted out the solution ??

**Comment by mr337** [comment]
Yeah I have and we are using it in our app. I also added a PR for our situation of running this on EC2 instances that have IAM role.

https://github.com/MetaMetricsInc/django-warrant/pull/9
